config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'chat_rooms#index'

  resources :chat_rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :first_participent, class_name: 'User'
  belongs_to :second_participent, class_name: 'User'

  def self.fetch_visible_rooms
    includes(:messages).where('first_participent_id = :current_user_id OR second_participent_id = :current_user_id', current_user_id: User.current_user)
  end

  def other_participent
    if first_participent_id == User.current_user.id
      second_participent
    else
      first_participent
    end
  end

  def last_message
    messages.last
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :sender, class_name: 'User'

  after_create_commit { broadcast_append_to 'messages' }  
  after_create_commit :notify_recipient
  before_destroy      :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  def self.fetch_messages(chat_room_id)
    where(chat_room_id: chat_room_id)
  end

  def recipient
    if sender_id != chat_room.first_participent_id
      chat_room.first_participent
    else
      chat_room.second_participent
    end
  end

  def notify_recipient
    unless recipient.online?
      MessageNotification.with(message: self, sender_id: sender_id).deliver_later(recipient)
    end
  end

  def cleanup_notifications
    notifications_as_message.destroy_all
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :exclude_current_user, -> { where.not(id: User.current_user&.id) }

  has_many :notifications, as: :recipient, dependent: :destroy

  after_create :create_chat_rooms

  def name
    "#{first_name} #{last_name}"
  end

  def self.current_user=(user)
    Thread.current[:current_user] = user
  end

  def self.current_user
    Thread.current[:current_user]
  end

  def self.fetch_users_without_chats(chat_rooms)
    exclude_current_user.where.not(id: chat_rooms.pluck(:first_participent_id, :second_participent_id).flatten.uniq)
  end

  def online?
    ActiveModel::Type::Boolean.new.cast($online_users.exists(id))
  end

  def create_chat_rooms
    User.where.not(id: id).each do |user|
      ChatRoom.create(first_participent_id: user.id, second_participent_id: id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :set_current_user
  before_action :set_online, unless: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_session_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def set_current_user
    User.current_user = current_user
  end

  # set to online
  def set_online
    if current_user
      $online_users.set(current_user.id, nil, ex: 5*60) # expires in 5 minutes
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  # GET chat_rooms/
  def index
    load_chat_room_components

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  private

  def load_chat_room_components
    @chat_rooms = ChatRoom.fetch_visible_rooms
  end

  def chat_room_params
    params.require(:chat_room).permit(:first_participent_id, :second_participent_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET chat_rooms/:id/messages/
  def index
    @chat_room = ChatRoom.find_by(id: params[:chat_room_id])
    @messages  = Message.fetch_messages(params[:chat_room_id])

    @chat_rooms = ChatRoom.fetch_visible_rooms

    respond_to do |format|
      format.html { render 'chat_rooms/index' }
      format.turbo_stream
    end
  end

  # chat_rooms/:id/messages/
  def create
    @message = Message.create(message_params)

    respond_to do |format|
      format.html { render 'chat_rooms/index' }
      format.turbo_stream
    end
  end

  private

  def message_params
    params.require(:message).permit(:sender_id, :body, :chat_room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_chat_room.html.erb
<%= link_to chat_room_messages_path(chat_room), class: dom_id(chat_room), method: :get, remote: true do %>
  <div class="flex justify-between items-center p-3 hover:bg-gray-800 rounded-lg relative">
    <div class="w-16 h-16 relative flex flex-shrink-0">
      <img class="shadow-md rounded-full w-full h-full object-cover" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt=""
        />
    </div>
    <div class="flex-auto min-w-0 ml-4 mr-2 hidden md:block group-hover:block">
      <p><%= chat_room.other_participent.name %></p>
      <div class="flex justify-between items-center text-sm text-gray-600">
        <div class="min-w-0">
          <p class="truncate"><%= chat_room.last_message&.body %></p>
        </div>
        <p class="ml-2"><%= time_ago_in_words(chat_room.last_message.updated_at) if chat_room.last_message&.updated_at.present? %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/chat_rooms/_messages.html.erb
<section class="flex flex-col flex-auto border-l border-gray-800">
  <div class="chat-header px-6 py-4 flex flex-row flex-none justify-between shadow">
    <div class="flex">
      <div class="w-12 h-12 mr-4 relative flex flex-shrink-0">
        <img class="shadow-md rounded-full w-full h-full object-cover" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt=""
          />
      </div>
      <div class="text-sm">
        <p class="font-bold"><%= participent_name.name %></p>
        <p>Active 1h ago</p>
      </div>
    </div>

    <div class="flex">
    </div>
  </div>
  <%= turbo_stream_from 'messages' %>
  <%= turbo_frame_tag 'messages', class: 'chat-body flex-1 overflow-y-scroll', data: { controller: 'scroll' } do %>
    <% if messages %>
      <%= render messages %>
    <% end %>
  <% end %>
  <div class="chat-footer flex-none">
    <%= form_for [chat_room, chat_room.messages.new], data: { controller: 'reset-form', action: "turbo:submit-end->reset-form#clear" }, remote: true do |f| %>
      <div class="flex flex-row items-center p-4">
        <div class="relative flex-grow">
          <label>
            <%= f.hidden_field :sender_id, value: user.id %>
            <%= f.hidden_field :chat_room_id, value: chat_room.id %>
            <%= f.text_field :body, class: 'rounded-full py-2 pl-5 pr-10 w-full border border-gray-800 focus:border-gray-700 bg-gray-800 focus:bg-gray-900 focus:outline-none text-gray-200 focus:shadow-md transition duration-300 ease-in', placeholder: 'Type a message' %>
          </label>
        </div>
        <%= button_tag type: 'submit', class: 'flex flex-shrink-0 focus:outline-none mx-2 block text-blue-600 hover:text-blue-700 w-6 h-6' do %>
          <svg class="origin-center transform rotate-90 w-full h-full fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
            </svg>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/chat_rooms/index.html.erb
<div class="h-screen w-full flex antialiased text-gray-200 bg-gray-900 overflow-hidden">
    <div class="flex-1 flex flex-col">
        <div class="border-b-2 border-gray-800 p-2 flex flex-row z-20 flex-row justify-between flex-none">
            <div class="flex justify-start ml-2"><%= current_user.name if user_signed_in? %></div>
            <div class="flex items-center">
              <div class="bg-red-600 w-3 h-3 rounded-full mr-2 justify-end"></div>
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'h-3 flex items-center mr-2 justify-end' %>
            </div>
        </div>
        <main class="flex-grow flex flex-row min-h-0">
            <section class="flex flex-col flex-none overflow-auto w-24 group lg:max-w-sm md:w-2/5 transition-all duration-300 ease-in-out">
                <div class="header p-4 flex flex-row justify-between items-center flex-none">
                    <div class="w-16 h-16 relative flex flex-shrink-0" style="filter: invert(100%);">
                        <img class="rounded-full w-full h-full object-cover" alt="ravisankarchinnam"
                             src="https://avatars3.githubusercontent.com/u/22351907?s=60"/>
                    </div>
                    <p class="text-md font-bold hidden md:block group-hover:block">Messenger</p>
                    <a href="#" class="block rounded-full hover:bg-gray-700 bg-gray-800 w-10 h-10 p-2 hidden md:block group-hover:block">
                        <svg viewBox="0 0 24 24" class="w-full h-full fill-current">
                            <path
                                    d="M6.3 12.3l10-10a1 1 0 0 1 1.4 0l4 4a1 1 0 0 1 0 1.4l-10 10a1 1 0 0 1-.7.3H7a1 1 0 0 1-1-1v-4a1 1 0 0 1 .3-.7zM8 16h2.59l9-9L17 4.41l-9 9V16zm10-2a1 1 0 0 1 2 0v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h6a1 1 0 0 1 0 2H4v14h14v-6z"/>
                        </svg>
                    </a>
                </div>
                <div class="search-box p-4 flex-none">
                    <form onsubmit="">
                        <div class="relative">
                            <label>
                                <input class="rounded-full py-2 pr-6 pl-10 w-full border border-gray-800 focus:border-gray-700 bg-gray-800 focus:bg-gray-900 focus:outline-none text-gray-200 focus:shadow-md transition duration-300 ease-in"
                                       type="text" value="" placeholder="Search Messenger"/>
                                <span class="absolute top-0 left-0 mt-2 ml-3 inline-block">
                                    <svg viewBox="0 0 24 24" class="w-6 h-6">
                                        <path fill="#bbb"
                                              d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"/>
                                    </svg>
                                </span>
                            </label>
                        </div>
                    </form>
                </div>
                <div class="contacts p-2 flex-1 overflow-y-scroll">
                  <% @chat_rooms.each do |chat_room| %>
                    <%= render chat_room %>
                  <% end %>
                </div>
            </section>
            <% if @chat_room.present? %>
              <%= render partial: 'chat_rooms/messages', locals: { messages: @messages, chat_room: @chat_room, user: User.current_user, participent_name: @chat_room.other_participent } %>
            <% end %>
        </main>
    </div>
</div>

app/views/layouts/_layout.html.erb
<style type="text/css">
  <% if current_user.present? %>
    <%= ".justify-content-#{current_user.id}" %> {
      justify-content:  flex-end;
    }
    <%= ".flex-row-reverse-#{current_user.id}" %> {
      justify-content:  flex-end;
    }
    <%= ".bg-blue-700-#{current_user.id}" %> {
      --tw-bg-opacity: 1 !important;
      background-color: rgb(29 78 216/var(--tw-bg-opacity)) !important;
    }
  <% end %>
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= render partial: 'layouts/layout' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice flex items-center justify-center text-gray-200 bg-gray-800 overflow-hidden py-3"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert flex items-center justify-center text-gray-200 bg-gray-800 overflow-hidden py-3"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="pr-4 pl-4 <%= dom_id(message) %>">
  <div class="flex flex-row justify-content-<%= message.sender_id %> mb-3">
    <div class="messages text-sm text-white grid grid-flow-row gap-2">
      <div class="flex items-center flex-row-reverse-<%= message.sender_id %> group">
        <p class="px-6 py-3 rounded-full bg-gray-800 bg-blue-700-<%= message.sender_id %> max-w-xs lg:max-w-md"><%= message.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/messages/_messages.html.erb
<% messages.each do |message| %>
  <%= render message %>
<% end %>

app/views/users/_user.html.erb
<%= form_for ChatRoom.new, html: { class: 'hover:bg-gray-800 p-3 rounded-lg relative' }, remote: true do |f| %>
  <%= f.hidden_field :first_participent_id, value: User.current_user.id %>
  <%= f.hidden_field :second_participent_id, value: user.id %>
  <%= button_tag type: 'submit' do %>
    <div class="flex justify-between items-center">
      <div class="w-16 h-16 relative flex flex-shrink-0">
        <img class="shadow-md rounded-full w-full h-full object-cover" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt=""/>
      </div>
      <div class="flex-auto min-w-0 ml-4 mr-2 hidden md:block group-hover:block">
        <p><%= user.name %></p>
      </div>
    </div>
  <% end %>
<% end %>